# Generated by Django 4.1.7 on 2023-04-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captiongrab', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawtranscript',
            unique_together={('title', 'text')},
        ),
    ]
