# Generated by Django 4.1.7 on 2023-04-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captiongrab', '0002_alter_rawtranscript_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawtranscript',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rawtranscript',
            name='vidId',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rawtranscript',
            unique_together={('title', 'vidId')},
        ),
        migrations.RemoveField(
            model_name='rawtranscript',
            name='text',
        ),
    ]
