# Generated by Django 4.1.7 on 2023-04-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captiongrab', '0003_alter_rawtranscript_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtranscript',
            name='transcript',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
